# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivrem', '0006_auto_20160611_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilePic',
            field=models.FileField(default='profile/egg.jpg', null=True, upload_to='profile/'),
        ),
    ]
