# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivrem', '0007_auto_20160614_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
