# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivrem', '0009_auto_20160614_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(help_text='Show us wadiyabi', upload_to='delivrem/%Y/%m/%d', verbose_name='pics'),
        ),
        migrations.AlterField(
            model_name='product',
            name='showoff',
            field=models.CharField(blank=True, max_length=440, null=True, verbose_name='shoutout'),
        ),
    ]
